### ISSUE TITLE
Update to Play 2.4

### ISSUE THREAD

**Issue by loicdescotte** [loicdescotte/Play2-HTML5Tags#16]
Current version is not compatible with Play 2.4 because of changes in the template engine.  
See https://www.playframework.com/documentation/2.4.x/Migration24

**Comment by wurstbrot** [comment]
Hi,

I really like your project and love to use it.
Do you know at which time you will be able to release a version for 2.4?
I've gone through the complete migration the last 3 days and now I stuck here ...

Kind regards,
Timo

**Comment by loicdescotte** [comment]
Hi,

I'm sorry but I don't have any time for the moment to work on this project, that's why I opened this issue, I hope some people (maybe you?) would be happy to contribute :)

However I hope I will have more time to work on this in a few months...

**Comment by loicdescotte** [comment]
Fixed in 2.4 branch 
https://github.com/loicdescotte/Play2-HTML5Tags/tree/2.4

**Comment by loicdescotte** [comment]
Fixed in master and release 1.2.2
